global:
  scrape_interval: 15s

scrape_configs:
  - job_name: otel-collector
    static_configs:
      - targets: ["otel-collector:9464"]
  - job_name: algorand
    metrics_path: /metrics
    static_configs:
      - targets: ["algorand-api:8080"]
  - job_name: datafeed
    metrics_path: /metrics
    static_configs:
      - targets: ["datafeed-api:8081"]
  - job_name: doordash
    metrics_path: /metrics
    static_configs:
      - targets: ["doordash-api:8082"]
  - job_name: terminal
    metrics_path: /api/metrics
    static_configs:
      - targets: ["terminal:3000"]
